---
# handlers file for ansible_otus
- name: restart nginx
  systemd: 
    name: nginx
    state: restarted
    enabled: yes
- name: reload nginx
  systemd: 
    name: nginx
    state: reloaded
- name: restart firewalld
  systemd: 
    name: firewalld
    state: restarted
