---
# handlers file for ansible_otus
- name: 'Старт nginx'
  systemd: 
    name: nginx
    state: started
    enabled: yes
- name: 'Перезапуск nginx'
  systemd: 
    name: nginx
    state: reloaded
- name: 'Перезапуск firewalld'
  systemd: 
    name: firewalld
    state: restarted
