---
# handlers file for ansible_otus
- name: start nginx
  systemd: 
    name: nginx
    state: started
    enabled: yes
- name: reload nginx
  systemd: 
    name: nginx
    state: reloaded
- name: restart firewalld
  systemd: 
    name: firewalld
    state: restarted
