---
# tasks file for ansible_otus
- name: 'Устанавливаем epel-release'
  yum: 
    name: epel-release
    state: present
- name: 'Ставим пакет nginx'
  yum: 
    name: nginx
    state: latest
  notify: 
    - start nginx
- name: Копируем конфиг nginx
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
- name: Открываем порт 8080 на firewalld
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
  notify: 
    - restart firewalld
